service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: ${env:REGION}
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(IAM/AuctionsTableIAM.yml):AuctionsTableIAM}


resources:
  Resources:
    AuctionsTable: ${file(Resources/AuctionsTable.yml):AuctionsTable}


functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  dotenv:
    path: ./.env
    basePath: ./
    logging: false
    include:
      - DYNAMODB_TABLE
      - REGION
  bundle:
    linting: false
