AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${env:DYNAMODB_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
